# Generated by Django 4.0.2 on 2022-02-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ad_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='labels',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('', 'default')], max_length=100),
        ),
    ]
