# Generated by Django 4.0.2 on 2022-02-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
